### PR TITLE
add Dockerfile to run webserver from Container

### PR DESCRIPTION
**Pull request by jsaalfeld**

### CODE REVIEW

**Comment by r0hi7** [comment]
Thanks, @jsaalfeld for this PR.
I am afraid I can't merge it yet. The reason is the way system is designed. Currently, the system works with the Docker API in the current host, so if the application is containerized itself, it will not be able to connect to the Docker socket and eventually will not be able to scan anything. But Once I add docker remote API, we are good to work on it.

**Comment by jsaalfeld** [comment]
I created the Dockerfile with a docker installation itself and in the documentation I noted, that the local docker-socket has to be mounted into the dockerfile. With that in place, you acces, thorough the running container, the docker engine on the hardware directly. So you can scan and access all things docker on your hardware through the container. I tested it on multiple machines and it works pretty well.

You can test it out by yourself.

**Comment by r0hi7** [comment]
Oh yeah, that makes sense. Would you mind rebasing it to the latest mater so that i can merge ?

**Comment by jsaalfeld** [comment]
Done

**Comment by r0hi7** [comment]
Merged. Thanks @jsaalfeld

**Pull request merged**
